#!/bin/bash
# My first script
ocamllex lexer.mll
menhir parser.mly
ocamlc -c ast.mli
ocamlc -c parser.mli
ocamlc -c parser.ml
ocamlc -c lexer.ml
ocamlc -c -o Askz3.cmo Askz3.ml
ocamlc -c Pretty.ml

ocamlc -c -o Promise.cmo JP/Promise.ml

ocamlc -c -o Rewriting.cmo  BackEnd/Rewriting.ml

ocamlc -c -o Forward.cmo  FrontEnd/Forward.ml

ocamlc -c -o sleek.cmo  BackEnd/sleek.ml

#ocamlc -c -o LTL_Traslator.cmo  LTL_Traslator.ml

ocamlc -o hip parser.cmo Askz3.cmo lexer.cmo Pretty.cmo Rewriting.cmo Forward.cmo

ocamlc -o sleek parser.cmo Askz3.cmo lexer.cmo Pretty.cmo Rewriting.cmo sleek.cmo

ocamlc -o promise Promise.cmo

#ocamlc -o ltl parser.cmo  lexer.cmo Pretty.cmo LTL_Traslator.cmo

rm *.cmi
rm *.cmo

rm lexer.ml
rm parser.ml
rm parser.mli



